site_name: GCES - É Fake
site_description: Documentação do projeto É Fake
site_url: https://gces-ehfake-fork.github.io/docs-interno/
use_directory_urls: true

# Repository
repo_name: GCES-EhFake-Fork/docs-interno
repo_url: https://github.com/GCES-EhFake-Fork/docs-interno

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - content.grid
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - Geral:
      - Comunidade Check-up:
          - Sobre: geral/check_up/index.md
          - Políticas da comunidade: geral/check_up/politicas.md
      - Comunidade RAG:
          - Sobre: geral/rag/index.md
  - Grupo - WebScrapping:
      - Sobre: grupo-webscrapping/index.md
      - Sprint 0:
          - Relatório Sprint 0: grupo-webscrapping/sprint0/relatorioSprint0.md
          - Diários de Bordo:
              - Alana Gabriele: grupo-webscrapping/sprint0/diarioAlana.md
              - Carlos Daniel: grupo-webscrapping/sprint0/diarioCarlos.md
              - Daniel Rodrigues: grupo-webscrapping/sprint0/diarioDaniel.md
              - Eduardo Ferreira: grupo-webscrapping/sprint0/diarioEduardo.md
              - Felipe de Sousa: grupo-webscrapping/sprint0/diarioFelipe.md
              - Gabriel Monteiro: grupo-webscrapping/sprint0/diarioGabriel.md
              - Lua Medeiros: grupo-webscrapping/sprint0/diarioLua.md
              - Luciano: grupo-webscrapping/sprint0/diarioLuciano.md
              - Pedro Henrique: grupo-webscrapping/sprint0/diarioPedro.md
  - Grupo - IA:
      - Sobre: grupo-ia/index.md
      - Sprint 0:
          - Relatório Sprint 0: grupo-ia/sprint0/relatorioSprint0.md
          - Diários de Bordo:
              - Pedro Ferreira: grupo-ia/sprint0/diarioPedroFerreira.md
              - Ana Catarina Santos: grupo-ia/sprint0/diarioAnaCatarina.md
