site_name: GCES - É Fake
site_description: Documentação do projeto É Fake
site_url: https://gces-ehfake-fork.github.io/docs-interno/
use_directory_urls: true

# Repository
repo_name: GCES-EhFake-Fork/docs-interno
repo_url: https://github.com/GCES-EhFake-Fork/docs-interno

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - content.grid
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - Comunidade Check-up:
    - Sobre: check-up/index.md
    - Políticas da Comunidade: check-up/politicas.md
  - Relatórios de Sprint:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md
      - Diários de Bordo:
          - Alana Gabriele: diarios/diarioAlana.md
          - Ana Catarina: diarios/diarioAnaCatarina.md
          - Carlos Daniel: diarios/diarioCarlos.md
          - Daniel Rodrigues: diarios/diarioDaniel.md
          - Eduardo Ferreira: diarios/diarioEduardo.md
          - Felipe de Sousa: diarios/diarioFelipe.md
          - Gabriel Monteiro: diarios/diarioGabriel.md
          - Lua Medeiros: diarios/diarioLua.md
          - Luciano: diarios/diarioLuciano.md
          - Mateus Levy: diarios/diarioMateusLevy.md
          - Pedro Ferreira: diarios/diarioPedroFerreira.md
          - Pedro Silva: diarios/diarioPedroSilva.md
          - Vinicius Alves: diarios/diarioVinicius.md
          - Yago Amin: diarios/diarioYago.md
        
